# Generated by Django 4.2.2 on 2023-06-16 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_avatar_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avatar",
                to="user.profile",
                verbose_name="profile",
            ),
        ),
    ]
