# Generated by Django 4.2.2 on 2023-06-19 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="src",
            new_name="image",
        ),
    ]
