# Generated by Django 4.2.2 on 2023-06-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_rename_src_productimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
