# Generated by Django 4.2.2 on 2023-06-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_product_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="limited_edition",
            field=models.BooleanField(default=False),
        ),
    ]
