# Generated by Django 4.2.2 on 2023-06-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_product_limited_edition"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="price",
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
    ]
